### ISSUE TITLE
How to pass JWT Token and Validate it?

### ISSUE THREAD

**Issue by saheel-ahmed** [SapphireDb/sapphiredb-js#11]
I used 

db.setAuthToken('');

after this unable to connect to the websocket.

Please help

**Comment by morrisjdev** [comment]
Hi.

Yes that's the correct method. If you want to clear the auth token call the function with null or let the paramters empty.

Did you also follow the guide for server setup? https://sapphire-db.com/security/net-core

The validation of an auth token is done by sapphiredb und you'll get an AuthTokenState in return when using the function above.

Here are the function headers for reference:
```
  public setAuthToken(authToken?: string): Observable<AuthTokenState>

public getAuthTokenState(): Observable<AuthTokenState>
```


Best regards

Morris
